version: "3"
services:
  listings-service:
    build: "./listings-service"
    depends_on:
      - listings-service-db
    volumes:
      - ./listings-service:/opt/app
  listings-service-db:
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20

  users-service:
    build: "./users-service"
    depends_on:
      - users-service-db
    volumes:
      - ./users-service:/opt/app

  users-service-db:
      platform: linux/x86_64
      environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=db
      image: mysql:5.7.20