version: "3"
services:
  api-gateway:
    build: "./api-gateway"
    depends_on:
      - listings-service
      - users-service
    ports:
      - 7000:7000
    volumes:
      - ./api-gateway:/opt/app

  listings-service:
    build: "./listings-service"
    depends_on:
      - listings-service-db
    environment:
      - DB_URI=mysql://root:password@listings-service-db/db?charset=UTF8
    ports:
      - 7100:7100
    volumes:
      - ./listings-service:/opt/app

  listings-service-db:
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7
    ports:
      - 0.0.0.0:7200:3306

  users-service:
    build: "./users-service"
    depends_on:
      - users-service-db
    environment:
      - DB_URI=mysql://root:password@users-service-db/db?charset=UTF8

    volumes:
      - ./users-service:/opt/app
    ports:
      - 7101:7101
  users-service-db:
      platform: linux/amd64
      environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=db
      image: mysql:5.7
      ports:
        - 0.0.0.0:7201:3306