version: "3"
services:
  listings-service:
    build: "./listings-service"
    depends_on:
      - listings-service-db
    volumes:
      - ./listings-service:/opt/app
  listings-service-db:
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:8.0.26
    ports:
      - 0.0.0.0:7200:3306

  users-service:
    build: "./users-service"
    depends_on:
      - users-service-db
    volumes:
      - ./users-service:/opt/app

  users-service-db:
      platform: linux/amd64
      environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=db
      image: mysql:8.0.26
      ports:
        - 0.0.0.0:7201:3306